name: 04 - Using Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build java
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: List files
        run: ls -l