name: 2 - Workflow Events Part1

on:
  # push:

  workflow_dispatch:

jobs:
  echo:
    name: Primeiro job criado
    runs-on: ubuntu-latest

    steps:
      - name: Show the trigger
        run: echo "O evento que acionou o workflow foi o ${{ github.event_name }}"
