name: 3 - Workflow Runners

on:
  # push:
  #   branches:
  #     - main

  workflow_dispatch:

jobs:
  ubuntu-echo:
    name: Job para rodar o workflow dentro da maquina auto hospedada do github - Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Show OS
        run: |
          echo "This job is running on an Ubuntu runner."
          echo "O runner que o job esta rodando é $RUNNER_OS"

  window-echo:
    name: Job para rodar o workflow dentro da maquina auto hospedada do github - Windows
    runs-on: windows-latest

    steps:
      - name: Show OS
        shell: bash
        run: |
          echo "This job is running on a Windows runner."
          echo "O runner que o job esta rodando é $RUNNER_OS"

  mac-echo:
    name: Job par rodar o workflow dentro da maquina auto hospedada do github - Mac
    runs-on: macos-latest

    steps:
      - name: Show OS
        run: |
          echo "This job is running on a MacOS runner."
          echo "O runner que o job esta rodando é $RUNNER_OS"

  verify-runner-context:
    name: Verificar runner que esta executando o workflow pelo contexto do github actions
    runs-on: ubuntu-latest

    steps:
      - name: Passo para verificar runner em execucao com contexto do github
        if: runner.os == 'Linux'
        run: echo "Este step roda somente em Linux"

  verify-runner-environment:
    name: Verificar runner que esta executando o workflow pela variavel de ambiente
    runs-on: windows-latest

    steps:
      - name: Step para verificar runner em execucao com variavel de ambiente
        shell: bash
        run: |
          echo "Verificando runner..."
          if [ $RUNNER_OS == "Linux" ]; then
            echo "É a maquina Linux em execução."
          elif [ $RUNNER_OS == "Windows" ]; then
            echo "É a maquina Windows em execução."
          else
            echo "É a maquina Mac em execução."
          fi

# Usar contextos do github actions fora de scripts bash (usar quando a decisao é do workflow)
# Usar variaveis de ambiente dentro de scripts bash (usar quando a decisao é dentro do script)

# Em blocos "if", nao usar "${{ runner.os }}" para usar o contexto do github actions, usar apenas "runner.os"
