name: 6 - Contexts

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  echo-data:
    name: Job para executar contextos
    runs-on: ubuntu-latest

    steps:
        - name: Display Information
          run: |
            echo "Event name: $GITHUB_EVENT_NAME"
            echo "Ref: $GITHUB_REF"
            echo "SHA: $GITHUB_SHA"
            echo "Actor: $GITHUB_ACTOR"
            echo "Workflow:"$GITHUB_WORKFLOW"
            echo "Run ID: $GITHUB_RUN_ID"
            echo "Run Number: $GITHUB_RUN_NUMBER"